[2025-07-07T01:42:36.246+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T01:42:34.873240+00:00 [queued]>
[2025-07-07T01:42:36.252+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T01:42:34.873240+00:00 [queued]>
[2025-07-07T01:42:36.252+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-07T01:42:36.279+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-07 01:42:34.873240+00:00
[2025-07-07T01:42:36.288+0000] {standard_task_runner.py:57} INFO - Started process 216 to run task
[2025-07-07T01:42:36.299+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'manual__2025-07-07T01:42:34.873240+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmp4xnu9ysi']
[2025-07-07T01:42:36.311+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask run_soda_scan
[2025-07-07T01:42:36.329+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T01:42:36.378+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T01:42:34.873240+00:00 [running]> on host 8bd9e7c694c8
[2025-07-07T01:42:36.483+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T01:42:34.873240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T01:42:34.873240+00:00'
[2025-07-07T01:42:36.485+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T01:42:36.488+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-07T01:42:36.502+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T01:42:36.506+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /home/***/.local/bin/soda: No such file or directory
[2025-07-07T01:42:36.506+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-07-07T01:42:36.516+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-07-07T01:42:36.531+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250707T014234, start_date=20250707T014236, end_date=20250707T014236
[2025-07-07T01:42:36.541+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task run_soda_scan (Bash command failed. The command returned a non-zero exit code 127.; 216)
[2025-07-07T01:42:36.553+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-07T01:42:36.569+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
