[2025-07-07T00:43:11.802+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T00:43:09.292599+00:00 [queued]>
[2025-07-07T00:43:11.810+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T00:43:09.292599+00:00 [queued]>
[2025-07-07T00:43:11.811+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-07T00:43:11.823+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-07 00:43:09.292599+00:00
[2025-07-07T00:43:11.833+0000] {standard_task_runner.py:57} INFO - Started process 628 to run task
[2025-07-07T00:43:11.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'manual__2025-07-07T00:43:09.292599+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmpzxwcz45k']
[2025-07-07T00:43:11.877+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask run_soda_scan
[2025-07-07T00:43:11.921+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T00:43:11.993+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-07T00:43:09.292599+00:00 [running]> on host 4010ea07c34f
[2025-07-07T00:43:12.154+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T00:43:09.292599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T00:43:09.292599+00:00'
[2025-07-07T00:43:12.157+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-07T00:43:12.163+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-07T00:43:12.186+0000] {subprocess.py:86} INFO - Output:
[2025-07-07T00:43:13.423+0000] {subprocess.py:93} INFO - [00:43:13] Soda Core 3.5.5
[2025-07-07T00:43:13.510+0000] {subprocess.py:93} INFO - [00:43:13] Scan summary:
[2025-07-07T00:43:13.511+0000] {subprocess.py:93} INFO - [00:43:13] 4/4 checks PASSED:
[2025-07-07T00:43:13.511+0000] {subprocess.py:93} INFO - [00:43:13]     dag_run in local_postgres
[2025-07-07T00:43:13.511+0000] {subprocess.py:93} INFO - [00:43:13]       row_count > 0 [PASSED]
[2025-07-07T00:43:13.511+0000] {subprocess.py:93} INFO - [00:43:13]       missing_count(dag_id) = 0 [PASSED]
[2025-07-07T00:43:13.511+0000] {subprocess.py:93} INFO - [00:43:13]       missing_count(execution_date) = 0 [PASSED]
[2025-07-07T00:43:13.512+0000] {subprocess.py:93} INFO - [00:43:13]       duplicate_count(run_id) = 0 [PASSED]
[2025-07-07T00:43:13.512+0000] {subprocess.py:93} INFO - [00:43:13] All is good. No failures. No warnings. No errors.
[2025-07-07T00:43:13.953+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-07T00:43:13.994+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250707T004309, start_date=20250707T004311, end_date=20250707T004313
[2025-07-07T00:43:14.042+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-07T00:43:14.068+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
