[2025-07-06T22:45:27.103+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T22:45:25.552898+00:00 [queued]>
[2025-07-06T22:45:27.109+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T22:45:25.552898+00:00 [queued]>
[2025-07-06T22:45:27.110+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-06T22:45:27.120+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-06 22:45:25.552898+00:00
[2025-07-06T22:45:27.131+0000] {standard_task_runner.py:57} INFO - Started process 359 to run task
[2025-07-06T22:45:27.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'manual__2025-07-06T22:45:25.552898+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmpa1ee7ft8']
[2025-07-06T22:45:27.143+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask run_soda_scan
[2025-07-06T22:45:27.168+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T22:45:27.202+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T22:45:25.552898+00:00 [running]> on host 4010ea07c34f
[2025-07-06T22:45:27.255+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T22:45:25.552898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T22:45:25.552898+00:00'
[2025-07-06T22:45:27.256+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T22:45:27.258+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-06T22:45:27.267+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T22:45:27.272+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /home/***/.local/bin/soda: No such file or directory
[2025-07-06T22:45:27.272+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-07-06T22:45:27.281+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-07-06T22:45:27.284+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250706T224525, start_date=20250706T224527, end_date=20250706T224527
[2025-07-06T22:45:27.293+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task run_soda_scan (Bash command failed. The command returned a non-zero exit code 127.; 359)
[2025-07-06T22:45:27.317+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-06T22:45:27.331+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
