[2025-07-06T23:26:08.057+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:26:07.080147+00:00 [queued]>
[2025-07-06T23:26:08.063+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:26:07.080147+00:00 [queued]>
[2025-07-06T23:26:08.063+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-06T23:26:08.070+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-06 23:26:07.080147+00:00
[2025-07-06T23:26:08.076+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2025-07-06T23:26:08.079+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'manual__2025-07-06T23:26:07.080147+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmpd04wv6g2']
[2025-07-06T23:26:08.081+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask run_soda_scan
[2025-07-06T23:26:08.093+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T23:26:08.118+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:26:07.080147+00:00 [running]> on host 4010ea07c34f
[2025-07-06T23:26:08.174+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T23:26:07.080147+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T23:26:07.080147+00:00'
[2025-07-06T23:26:08.175+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T23:26:08.176+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-06T23:26:08.184+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T23:26:09.046+0000] {subprocess.py:93} INFO - [23:26:09] Soda Core 3.5.5
[2025-07-06T23:26:09.101+0000] {subprocess.py:93} INFO - [23:26:09] Scan summary:
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09] 4/4 checks PASSED:
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09]     dag_run in local_postgres
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09]       row_count > 0 [PASSED]
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09]       missing_count(dag_id) = 0 [PASSED]
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09]       missing_count(execution_date) = 0 [PASSED]
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09]       duplicate_count(run_id) = 0 [PASSED]
[2025-07-06T23:26:09.102+0000] {subprocess.py:93} INFO - [23:26:09] All is good. No failures. No warnings. No errors.
[2025-07-06T23:26:09.561+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-06T23:26:09.590+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250706T232607, start_date=20250706T232608, end_date=20250706T232609
[2025-07-06T23:26:09.631+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-06T23:26:09.647+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
