[2025-07-06T23:10:26.467+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:10:25.502690+00:00 [queued]>
[2025-07-06T23:10:26.471+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:10:25.502690+00:00 [queued]>
[2025-07-06T23:10:26.471+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-06T23:10:26.478+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_soda_scan> on 2025-07-06 23:10:25.502690+00:00
[2025-07-06T23:10:26.488+0000] {standard_task_runner.py:57} INFO - Started process 322 to run task
[2025-07-06T23:10:26.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'soda_scan_example', 'run_soda_scan', 'manual__2025-07-06T23:10:25.502690+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/soda_scan_dag.py', '--cfg-path', '/tmp/tmph0h5rome']
[2025-07-06T23:10:26.498+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask run_soda_scan
[2025-07-06T23:10:26.509+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T23:10:26.558+0000] {task_command.py:415} INFO - Running <TaskInstance: soda_scan_example.run_soda_scan manual__2025-07-06T23:10:25.502690+00:00 [running]> on host 4010ea07c34f
[2025-07-06T23:10:26.623+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soda_scan_example' AIRFLOW_CTX_TASK_ID='run_soda_scan' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T23:10:25.502690+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T23:10:25.502690+00:00'
[2025-07-06T23:10:26.625+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-06T23:10:26.626+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'export PATH=$PATH:/home/***/.local/bin && /home/***/.local/bin/soda scan -d local_postgres -c /usr/local/soda/config.yml /usr/local/soda/scan_checks.yml']
[2025-07-06T23:10:26.633+0000] {subprocess.py:86} INFO - Output:
[2025-07-06T23:10:27.570+0000] {subprocess.py:93} INFO - [23:10:27] Soda Core 3.5.5
[2025-07-06T23:10:27.637+0000] {subprocess.py:93} INFO - [23:10:27] Scan summary:
[2025-07-06T23:10:27.637+0000] {subprocess.py:93} INFO - [23:10:27] 4/4 checks PASSED:
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27]     dag_run in local_postgres
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27]       row_count > 0 [PASSED]
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27]       missing_count(dag_id) = 0 [PASSED]
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27]       missing_count(execution_date) = 0 [PASSED]
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27]       duplicate_count(run_id) = 0 [PASSED]
[2025-07-06T23:10:27.638+0000] {subprocess.py:93} INFO - [23:10:27] All is good. No failures. No warnings. No errors.
[2025-07-06T23:10:28.045+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-06T23:10:28.067+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=soda_scan_example, task_id=run_soda_scan, execution_date=20250706T231025, start_date=20250706T231026, end_date=20250706T231028
[2025-07-06T23:10:28.117+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-06T23:10:28.132+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
